export {default as Home } from './home/Home'
export {default as Login } from './login/Login'
export {default as Profile } from './profile/Profile'
export {default as ProfileEdit } from './profileEdit/ProfileEdit'
export {default as Register } from './register/Register'
export {default as About } from './about/About'